# Generated by Django 3.2.1 on 2022-10-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='likes'),
        ),
    ]
